### PR TITLE
Update rpi-rgb-led-matrix to latest version.

### PR DESCRIPTION
**Pull request by hzeller**
Hi Tony,

I am the maintainer of the rpi-rgb-led-matrix code you are using and recently got requests how to use the more recently added flags in the rpi-rgb-led-matrix.

So I have updated your project to use the latest version of the matrix library and also allow to just use the standard flags from the library (which involves geometry, such as `--led-rows` or `--led-chains` but also choice of type of HAT via a flag). These parameters can be overridden by the configuration file, but it is not necessary anymore to have a configuration file if the set-up is simple; e.g. in my case (with three parallel chains of 5 32x32 displays each), I can just run it like this:
```
sudo ./rpi-fb-matrix --led-gpio-mapping=regular --led-slowdown-gpio=2 --led-chain=5 --led-parallel=3
```

(The defaut hardware mapping is, as it used to be `adafruit-hat`, so I have to manually override that with `--led-gpio-mapping=regular` above.)

You can even run it as a daemon with the `--led-daemon` option, which might make sense for common use-cases.

Anyway, I made a pull-request out of it for your consideration.

Cheers,
  Henner.

### CODE REVIEW

**Comment by thorlancaster** [comment]
This update makes rpi-fb-matrix work great. In my opinion, this pull request should definitely be accepted.

**Comment by hzeller** [comment]
Ping. Did you try it @tdicola ?

**Comment by hzeller** [comment]
Ping...
This would really be good to merge.

**Comment by polygonfuture** [comment]
Ping!!  Please accept this pull request!

**Comment by hzeller** [comment]
Nothing happened so far, so I have again updated to the latest version of the library.
Please merge this change, so that people are not stuck with an ancient version.

**Comment by ladyada** [comment]
thx we'll take a look :)

**Comment by hzeller** [comment]
Cool!
Since it accumulated a couple of commits, I suggest to use the "Squash and Merge" option in github, or if you do it manually, to squash all the commits.

**Comment by ladyada** [comment]
ok we have to do hardware testing (of course :) so it may take a bit.

to-be-commenters: please use the thumbs-up button instead of replying with +1 and 'ping' - thanks :)

**Comment by hzeller** [comment]
Regarding hardware: I have set the default hardware mapping to `--led-gpio-mapping=adafruit-hat` so it should work right out of the box with the HAT as before.

(to get the default mapping of the rpi-rgb-led-matrix, users explicitly have to choose `--led-gpio-mapping=regular`).

**Pull request merged**
